apiVersion: v1
kind: Service
metadata:
 annotations:
   prometheus.io/port: "8082"
   prometheus.io/scrape: "true"
 labels:
   app: worker-push-api-python
 name: worker-push-api-python
 namespace: default
spec:
 ports:
 - name: metrics
   port: 8082
   protocol: TCP
   targetPort: metrics
 selector:
   app: worker-push-api-python
 type: ClusterIP